from math import sqrt,sin,pow,pi,e
import math
print(dir(math))
x=12
y=81
# ........ use of square root...........
print(sqrt(y))
#......... use sin function.............
print(sin(x))
#.......... use of power function........
print(pow(x,y))
#.......... value of pi..........
print(pi)
#.......... value of exponential.......
print(e)